import 'package:dio/dio.dart' show FormData;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kagoem_pos_mobile/app.dart';

import '../../data/catalog_repository_test.dart' show page, productJson;
import '../../helpers/fake_backend.dart';
import '../../helpers/test_app.dart';

Map<String, String> fields(Object? data) => {for (final e in (data as FormData).fields) e.key: e.value};

void main() {
  late TestHarness h;

  setUp(() async {
    h = TestHarness();
    await h.session.saveToken('5|tok');
    h.backend.reply('GET', '/tenants', 200, ok([tenantJson()]));
    h.backend.reply('GET', '/settings', 200, ok(<String, dynamic>{}));
    h.backend.reply('GET', '/dashboard', 200, ok({'stats': <String, dynamic>{}}));
    h.backend.reply('GET', '/categories', 200, page([
      {'id': 2, 'name': 'Minuman', 'slug': 'minuman', 'is_active': true},
    ]));
    h.backend.reply('GET', '/brands', 200, page([
      {'id': 1, 'name': 'Kagoem'},
    ]));
    h.backend.reply('GET', '/units', 200, page([
      {'id': 1, 'name': 'pcs'},
    ]));
    h.backend.reply('GET', '/products', 200, page([]));
  });

  Future<void> openProducts(WidgetTester tester, List<String> permissions) async {
    h.backend.reply('GET', '/auth/me', 200, ok(userJson(permissions: permissions)));
    tester.view.physicalSize = const Size(480, 1400);
    tester.view.devicePixelRatio = 1;
    addTearDown(tester.view.reset);
    await tester.pumpWidget(ProviderScope(overrides: h.overrides, retry: (_, _) => null, child: const KagoemPosApp()));
    await tester.pumpAndSettle();
    final menu = find.widgetWithText(InkWell, 'Produk');
    await tester.scrollUntilVisible(menu, 200, scrollable: find.byType(Scrollable).first);
    await tester.tap(menu);
    await tester.pumpAndSettle();
  }

  Future<void> choose(WidgetTester tester, String label, String option) async {
    await tester.tap(find.widgetWithText(DropdownButtonFormField<int>, label));
    await tester.pumpAndSettle();
    await tester.tap(find.text(option).last);
    await tester.pumpAndSettle();
  }

  Future<void> fillRequired(WidgetTester tester) async {
    await tester.tap(find.byKey(const Key('product-add')));
    await tester.pumpAndSettle();
    await tester.enterText(find.byKey(const Key('edit-name')), 'Teh Botol');
    await tester.enterText(find.byKey(const Key('edit-sku')), 'TEH-02');
    await choose(tester, 'Kategori *', 'Minuman');
    await choose(tester, 'Merek *', 'Kagoem');
    await choose(tester, 'Satuan *', 'pcs');
    await tester.enterText(find.byKey(const Key('edit-price')), '5000');
    await tester.enterText(find.byKey(const Key('edit-cost')), '3500');
  }

  testWidgets('a Kasir cannot add products', (tester) async {
    await openProducts(tester, ['manage-sales', 'operate-cash-drawer']);
    expect(find.byKey(const Key('product-add')), findsNothing);
  });

  testWidgets('required fields are checked before anything is sent', (tester) async {
    await openProducts(tester, ['manage-sales', 'manage-products']);
    await tester.tap(find.byKey(const Key('product-add')));
    await tester.pumpAndSettle();
    expect(find.text('Tambah Produk'), findsWidgets);

    await tester.tap(find.byKey(const Key('edit-save')));
    await tester.pumpAndSettle();

    expect(find.text('Wajib diisi.'), findsNWidgets(4)); // name, SKU, sale price, cost price
    expect(find.text('Wajib dipilih.'), findsNWidgets(3)); // category, brand, unit
    expect(h.backend.calls('POST', '/products'), isEmpty);
  });

  testWidgets('Owner adds a product with web defaults; empty barcode is generated by the server', (tester) async {
    h.backend.on('POST', '/products', (r) {
      final f = fields(r.data);
      return (status: 201, body: ok(productJson(id: 9, name: f['name']!, sku: f['sku']!, price: 5000)));
    });
    await openProducts(tester, ['manage-sales', 'manage-products']);
    await fillRequired(tester);
    await tester.tap(find.byKey(const Key('edit-save')));
    await tester.pumpAndSettle();

    final request = h.backend.calls('POST', '/products').single;
    expect(fields(request.data), {
      'name': 'Teh Botol',
      'sku': 'TEH-02',
      'category_id': '2',
      'brand_id': '1',
      'unit_id': '1',
      'price': '5000',
      'cost_price': '3500',
      'stock': '0',
      'min_stock': '0',
      'tax_percentage': '11',
      'discount_percentage': '0',
      'is_active': '1',
    });
    expect(find.text('Produk Teh Botol ditambahkan.'), findsOneWidget);
    expect(find.text('Tambah Produk'), findsOneWidget); // back on the list (FAB label)
    // The catalog is reloaded to show the new product.
    expect(h.backend.calls('GET', '/products').length, greaterThan(1));
  });

  testWidgets('plan product limit (SaaS) is shown as a message', (tester) async {
    const limit = 'Batas produk untuk paket starter sudah tercapai (maksimal 100). Upgrade paket untuk menambah produk.';
    h.backend.reply('POST', '/products', 422, {
      'success': false,
      'message': limit,
      'code': 'PLAN_LIMIT_REACHED',
      'errors': {
        'product': [limit],
      },
    });
    await openProducts(tester, ['manage-sales', 'manage-products']);
    await fillRequired(tester);
    await tester.tap(find.byKey(const Key('edit-save')));
    await tester.pumpAndSettle();

    expect(find.text(limit), findsOneWidget);
    expect(find.text('Teh Botol'), findsOneWidget, reason: 'form kept for another try');
  });

  testWidgets('SKU already used is shown on the field', (tester) async {
    h.backend.reply('POST', '/products', 422, validationError({
      'sku': ['The sku has already been taken.'],
    }));
    await openProducts(tester, ['manage-sales', 'manage-products']);
    await fillRequired(tester);
    await tester.tap(find.byKey(const Key('edit-save')));
    await tester.pumpAndSettle();
    expect(find.text('SKU sudah dipakai produk lain.'), findsOneWidget);
  });
}
